Old = [
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 17},
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 17},
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 17},
    {'dt_code': 'Conveyor VFD 1 Faulted', 'fault_code': 1001},
    {'dt_code': 'Conveyor VFD 1 Faulted', 'fault_code': 1001},
    {'dt_code': 'PROCESS FAULT - AGC 1', 'fault_code': 1001},
    {'dt_code': 'PROCESS FAULT - AGC 2', 'fault_code': 1002},
    {'dt_code': 'PROCESS FAULT - AGC 3', 'fault_code': 1003},
    {'dt_code': 'PROCESS FAULT - AGC 4', 'fault_code': 1004},
    {'dt_code': 'PROCESS FAULT - AGC 5', 'fault_code': 1005},
    {'dt_code': 'PROCESS FAULT - AGC 6', 'fault_code': 1006},
    {'dt_code': 'PROCESS FAULT - AGC 7', 'fault_code': 1007},
    {'dt_code': 'PROCESS FAULT - AGC 8', 'fault_code': 1008},
    {'dt_code': 'PROCESS FAULT - AGC 9', 'fault_code': 1009},
    {'dt_code': 'PROCESS FAULT - AGC 10', 'fault_code': 1010},
    {'dt_code': 'PROCESS FAULT - AGC 11', 'fault_code': 1011},
    {'dt_code': 'PROCESS FAULT - AGC 12', 'fault_code': 1012},
    {'dt_code': 'PROCESS FAULT - AGC 13', 'fault_code': 1013},
    {'dt_code': 'PROCESS FAULT - AGC 14', 'fault_code': 1014},
    {'dt_code': 'INVALID RUN MODE SELECTED', 'fault_code': 1101},
    {'dt_code': 'ELEC FAULT - STA 41', 'fault_code': 1101},
    {'dt_code': 'ELEC FAULT - STA 11', 'fault_code': 1101},
    {'dt_code': 'ELEC FAULT - STA 31', 'fault_code': 1101},
    {'dt_code': 'ELEC FAULT - STA 32', 'fault_code': 1102},
    {'dt_code': 'ELEC FAULT - STA 12', 'fault_code': 1102},
    {'dt_code': 'ELEC FAULT - STA 42', 'fault_code': 1102},
    {'dt_code': 'ELEC FAULT - STA 43', 'fault_code': 1103},
    {'dt_code': 'ELEC FAULT - STA 13', 'fault_code': 1103},
    {'dt_code': 'ELEC FAULT - STA 33', 'fault_code': 1103},
    {'dt_code': 'ELEC FAULT - STA 34', 'fault_code': 1104},
    {'dt_code': 'ELEC FAULT - STA 14', 'fault_code': 1104},
    {'dt_code': 'ELEC FAULT - STA 44', 'fault_code': 1104},
    {'dt_code': 'ELEC FAULT - STA 45', 'fault_code': 1105},
    {'dt_code': 'ELEC FAULT - STA 15', 'fault_code': 1105},
    {'dt_code': 'ELEC FAULT - STA 35', 'fault_code': 1105},
    {'dt_code': 'ELEC FAULT - STA 36', 'fault_code': 1106},
    {'dt_code': 'ELEC FAULT - STA 16', 'fault_code': 1106},
    {'dt_code': 'ELEC FAULT - STA 46', 'fault_code': 1106},
    {'dt_code': 'ELEC FAULT - STA 47', 'fault_code': 1107},
    {'dt_code': 'ELEC FAULT - STA 17', 'fault_code': 1107},
    {'dt_code': 'ELEC FAULT - STA 37', 'fault_code': 1107},
    {'dt_code': 'ELEC FAULT - STA 38', 'fault_code': 1108},
    {'dt_code': 'ELEC FAULT - STA 18', 'fault_code': 1108},
    {'dt_code': 'ELEC FAULT - STA 48', 'fault_code': 1108},
    {'dt_code': 'ELEC FAULT - STA 49', 'fault_code': 1109},
    {'dt_code': 'ELEC FAULT - STA 19', 'fault_code': 1109},
    {'dt_code': 'ELEC FAULT - STA 39', 'fault_code': 1109},
    {'dt_code': 'ELEC FAULT - STA 40', 'fault_code': 1110},
    {'dt_code': 'ELEC FAULT - STA 20', 'fault_code': 1110},
    {'dt_code': 'ELEC FAULT - STA 50', 'fault_code': 1110},
    {'dt_code': 'ELEC FAULT - STA 51', 'fault_code': 1111},
    {'dt_code': 'ELEC FAULT - STA 21', 'fault_code': 1111},
    {'dt_code': 'ELEC FAULT - REPAIR IN', 'fault_code': 1111},
    {'dt_code': 'ELEC FAULT - REPAIR OUT', 'fault_code': 1112},
    {'dt_code': 'ELEC FAULT - STA 22', 'fault_code': 1112},
    {'dt_code': 'ELEC FAULT - STA 52', 'fault_code': 1112},
    {'dt_code': 'ELEC FAULT - STA 53', 'fault_code': 1113},
    {'dt_code': 'ELEC FAULT - STA 23', 'fault_code': 1113},
    {'dt_code': 'ELEC FAULT - TCI', 'fault_code': 1113},
    {'dt_code': 'ELEC FAULT - STA 24', 'fault_code': 1114},
    {'dt_code': 'ELEC FAULT - STA 54', 'fault_code': 1114},
    {'dt_code': 'ELEC FAULT - STA 55', 'fault_code': 1115},
    {'dt_code': 'ELEC FAULT - STA 25', 'fault_code': 1115},
    {'dt_code': 'ELEC FAULT - STA 26', 'fault_code': 1116},
    {'dt_code': 'ELEC FAULT - STA 56', 'fault_code': 1116},
    {'dt_code': 'ELEC FAULT - STA 57', 'fault_code': 1117},
    {'dt_code': 'ELEC FAULT - STA 27', 'fault_code': 1117},
    {'dt_code': 'ELEC FAULT - STA 28', 'fault_code': 1118},
    {'dt_code': 'ELEC FAULT - STA 58', 'fault_code': 1118},
    {'dt_code': 'ELEC FAULT - STA 59', 'fault_code': 1119},
    {'dt_code': 'ELEC FAULT - STA 29', 'fault_code': 1119},
    {'dt_code': 'ELEC FAULT - STA 30', 'fault_code': 1120},
    {'dt_code': 'ELEC FAULT - STA 60', 'fault_code': 1120},
    {'dt_code': 'ELEC FAULT - REPAIR IN/OUT', 'fault_code': 1121},
    {'dt_code': 'PROCESS FAULT - LOAD STA', 'fault_code': 1201},
    {'dt_code': 'PROCESS FAULT - VISION STA', 'fault_code': 1202},
    {'dt_code': 'PROCESS FAULT - STA 1', 'fault_code': 1203},
    {'dt_code': 'PROCESS FAULT - STA 2', 'fault_code': 1204},
    {'dt_code': 'PROCESS FAULT - STA 3', 'fault_code': 1205},
    {'dt_code': 'PROCESS FAULT - STA 4', 'fault_code': 1206},
    {'dt_code': 'PROCESS FAULT - STA 5', 'fault_code': 1207},
    {'dt_code': 'PROCESS FAULT - STA 6', 'fault_code': 1208},
    {'dt_code': 'PROCESS FAULT - STA 7', 'fault_code': 1209},
    {'dt_code': 'PROCESS FAULT - UNLOAD', 'fault_code': 1210},
    {'dt_code': 'PROCESS FAULT - LOAD HLDBACK', 'fault_code': 1211},
    {'dt_code': 'PROCESS FAULT - VISION HLDBACK', 'fault_code': 1212},
    {'dt_code': 'NO PART AT STA 1 HOLDBACK', 'fault_code': 1213},
    {'dt_code': 'PROCESS FAULT - UNLOAD HLDBACK', 'fault_code': 1214},
    {'dt_code': 'ESTOP - AGC 1', 'fault_code': 1301},
    {'dt_code': 'ESTOP - AGC 2', 'fault_code': 1302},
    {'dt_code': 'ESTOP - AGC 3', 'fault_code': 1303},
    {'dt_code': 'ESTOP - AGC 4', 'fault_code': 1304},
    {'dt_code': 'ESTOP - AGC 5', 'fault_code': 1305},
    {'dt_code': 'ESTOP - AGC 6', 'fault_code': 1306},
    {'dt_code': 'ESTOP - AGC 7', 'fault_code': 1307},
    {'dt_code': 'ESTOP - AGC 8', 'fault_code': 1308},
    {'dt_code': 'ESTOP - AGC 9', 'fault_code': 1309},
    {'dt_code': 'ESTOP - AGC 10', 'fault_code': 1310},
    {'dt_code': 'ESTOP - AGC 11', 'fault_code': 1311},
    {'dt_code': 'ESTOP - AGC 12', 'fault_code': 1312},
    {'dt_code': 'ESTOP - AGC 13', 'fault_code': 1313},
    {'dt_code': 'ESTOP - AGC 14', 'fault_code': 1314},
    {'dt_code': 'SEND AGC 1 TO MAINT', 'fault_code': 1401},
    {'dt_code': 'SEND AGC 2 TO MAINT', 'fault_code': 1402},
    {'dt_code': 'SEND AGC 3 TO MAINT', 'fault_code': 1403},
    {'dt_code': 'SEND AGC 4 TO MAINT', 'fault_code': 1404},
    {'dt_code': 'SEND AGC 5 TO MAINT', 'fault_code': 1405},
    {'dt_code': 'SEND AGC 6 TO MAINT', 'fault_code': 1406},
    {'dt_code': 'SEND AGC 7 TO MAINT', 'fault_code': 1407},
    {'dt_code': 'SEND AGC 8 TO MAINT', 'fault_code': 1408},
    {'dt_code': 'SEND AGC 9 TO MAINT', 'fault_code': 1409},
    {'dt_code': 'SEND AGC 10 TO MAINT', 'fault_code': 1410},
    {'dt_code': 'SEND AGC 11 TO MAINT', 'fault_code': 1411},
    {'dt_code': 'SEND AGC 12 TO MAINT', 'fault_code': 1412},
    {'dt_code': 'SEND AGC 13 TO MAINT', 'fault_code': 1413},
    {'dt_code': 'SEND AGC 14 TO MAINT', 'fault_code': 1414},
    {'dt_code': 'BLOCKED - AGC 1', 'fault_code': 2001},
    {'dt_code': 'BLOCKED - AGC 2', 'fault_code': 2002},
    {'dt_code': 'BLOCKED - AGC 3', 'fault_code': 2003},
    {'dt_code': 'BLOCKED - AGC 4', 'fault_code': 2004},
    {'dt_code': 'BLOCKED - AGC 5', 'fault_code': 2005},
    {'dt_code': 'BLOCKED - AGC 6', 'fault_code': 2006},
    {'dt_code': 'BLOCKED - AGC 7', 'fault_code': 2007},
    {'dt_code': 'BLOCKED - AGC 8', 'fault_code': 2008},
    {'dt_code': 'BLOCKED - AGC 9', 'fault_code': 2009},
    {'dt_code': 'BLOCKED - AGC 10', 'fault_code': 2010},
    {'dt_code': 'BLOCKED - AGC 11', 'fault_code': 2011},
    {'dt_code': 'BLOCKED - AGC 12', 'fault_code': 2012},
    {'dt_code': 'BLOCKED - AGC 13', 'fault_code': 2013},
    {'dt_code': 'BLOCKED - AGC 14', 'fault_code': 2014},
    {'dt_code': 'MECH FAULT - STA 41', 'fault_code': 2101},
    {'dt_code': 'MECH FAULT - STA 11', 'fault_code': 2101},
    {'dt_code': 'MECH FAULT - STA 31', 'fault_code': 2101},
    {'dt_code': 'MECH FAULT - STA 32', 'fault_code': 2102},
    {'dt_code': 'MECH FAULT - STA 12', 'fault_code': 2102},
    {'dt_code': 'MECH FAULT - STA 42', 'fault_code': 2102},
    {'dt_code': 'MECH FAULT - STA 43', 'fault_code': 2103},
    {'dt_code': 'MECH FAULT - STA 13', 'fault_code': 2103},
    {'dt_code': 'MECH FAULT - STA 33', 'fault_code': 2103},
    {'dt_code': 'MECH FAULT - STA 34', 'fault_code': 2104},
    {'dt_code': 'MECH FAULT - STA 14', 'fault_code': 2104},
    {'dt_code': 'MECH FAULT - STA 44', 'fault_code': 2104},
    {'dt_code': 'MECH FAULT - STA 45', 'fault_code': 2105},
    {'dt_code': 'MECH FAULT - STA 15', 'fault_code': 2105},
    {'dt_code': 'MECH FAULT - STA 35', 'fault_code': 2105},
    {'dt_code': 'MECH FAULT - STA 36', 'fault_code': 2106},
    {'dt_code': 'MECH FAULT - STA 16', 'fault_code': 2106},
    {'dt_code': 'MECH FAULT - STA 46', 'fault_code': 2106},
    {'dt_code': 'MECH FAULT - STA 47', 'fault_code': 2107},
    {'dt_code': 'MECH FAULT - STA 17', 'fault_code': 2107},
    {'dt_code': 'MECH FAULT - STA 37', 'fault_code': 2107},
    {'dt_code': 'MECH FAULT - STA 38', 'fault_code': 2108},
    {'dt_code': 'MECH FAULT - STA 18', 'fault_code': 2108},
    {'dt_code': 'MECH FAULT - STA 48', 'fault_code': 2108},
    {'dt_code': 'MECH FAULT - STA 49', 'fault_code': 2109},
    {'dt_code': 'MECH FAULT - STA 19', 'fault_code': 2109},
    {'dt_code': 'MECH FAULT - STA 39', 'fault_code': 2109},
    {'dt_code': 'MECH FAULT - STA 40', 'fault_code': 2110},
    {'dt_code': 'MECH FAULT - STA 20', 'fault_code': 2110},
    {'dt_code': 'MECH FAULT - STA 50', 'fault_code': 2110},
    {'dt_code': 'MECH FAULT - STA 51', 'fault_code': 2111},
    {'dt_code': 'MECH FAULT - STA 21', 'fault_code': 2111},
    {'dt_code': 'MECH FAULT - REPAIR IN', 'fault_code': 2111},
    {'dt_code': 'MECH FAULT - REPAIR OUT', 'fault_code': 2112},
    {'dt_code': 'MECH FAULT - STA 22', 'fault_code': 2112},
    {'dt_code': 'MECH FAULT - STA 52', 'fault_code': 2112},
    {'dt_code': 'MECH FAULT - STA 53', 'fault_code': 2113},
    {'dt_code': 'MECH FAULT - STA 23', 'fault_code': 2113},
    {'dt_code': 'MECH FAULT TCI', 'fault_code': 2113},
    {'dt_code': 'MECH FAULT - STA 24', 'fault_code': 2114},
    {'dt_code': 'MECH FAULT - STA 54', 'fault_code': 2114},
    {'dt_code': 'MECH FAULT - STA 55', 'fault_code': 2115},
    {'dt_code': 'MECH FAULT - STA 25', 'fault_code': 2115},
    {'dt_code': 'MECH FAULT - STA 26', 'fault_code': 2116},
    {'dt_code': 'MECH FAULT - STA 56', 'fault_code': 2116},
    {'dt_code': 'MECH FAULT - STA 57', 'fault_code': 2117},
    {'dt_code': 'MECH FAULT - STA 27', 'fault_code': 2117},
    {'dt_code': 'MECH FAULT - STA 28', 'fault_code': 2118},
    {'dt_code': 'MECH FAULT - STA 58', 'fault_code': 2118},
    {'dt_code': 'MECH FAULT - STA 59', 'fault_code': 2119},
    {'dt_code': 'MECH FAULT - STA 29', 'fault_code': 2119},
    {'dt_code': 'MECH FAULT - STA 30', 'fault_code': 2120},
    {'dt_code': 'MECH FAULT - STA 60', 'fault_code': 2120},
    {'dt_code': 'MECH FAULT - REPAIR IN/OUT', 'fault_code': 2121},
    {'dt_code': 'STA 11 SAFETY SCANNER', 'fault_code': 2121},
    {'dt_code': 'STA 24 SAFETY SCANNER', 'fault_code': 2122},
    {'dt_code': 'STA 28 SAFETY SCANNER', 'fault_code': 2123},
    {'dt_code': 'COM FAULT - CONV ZONE 1', 'fault_code': 5001},
    {'dt_code': 'COM FAULT - CONV ZONE 3', 'fault_code': 5001},
    {'dt_code': 'COM FAULT - AGC 1', 'fault_code': 5001},
    {'dt_code': 'COM FAULT - CONV ZONE 2', 'fault_code': 5001},
    {'dt_code': 'COM FAULT - AGC 2', 'fault_code': 5002},
    {'dt_code': 'COM FAULT - AGC 3', 'fault_code': 5003},
    {'dt_code': 'COM FAULT - AGC 4', 'fault_code': 5004},
    {'dt_code': 'COM FAULT - AGC 5', 'fault_code': 5005},
    {'dt_code': 'COM FAULT - AGC 6', 'fault_code': 5006},
    {'dt_code': 'COM FAULT - AGC 7', 'fault_code': 5007},
    {'dt_code': 'COM FAULT - AGC 8', 'fault_code': 5008},
    {'dt_code': 'COM FAULT - AGC 9', 'fault_code': 5009},
    {'dt_code': 'COM FAULT - AGC 10', 'fault_code': 5010},
    {'dt_code': 'COM FAULT - AGC 11', 'fault_code': 5011},
    {'dt_code': 'COM FAULT - AGC 12', 'fault_code': 5012},
    {'dt_code': 'COM FAULT - AGC 13', 'fault_code': 5013},
    {'dt_code': 'COM FAULT - AGC 14', 'fault_code': 5014},
    {'dt_code': 'COM FAULT - PLC CARDS', 'fault_code': 5015},
    {'dt_code': 'COM FAULT - L51POSTFOAM PLC', 'fault_code': 5016},
    {'dt_code': 'COM FAULT - L52CONV PLC', 'fault_code': 5017},
    {'dt_code': 'COM FAULT - EFLEX', 'fault_code': 5018},
    {'dt_code': 'COM FAULT - SAM', 'fault_code': 5019},
    {'dt_code': 'COM FAULT - EFLEX MODULE', 'fault_code': 5020},
    {'dt_code': 'STARVED- LOAD STA.', 'fault_code': 10001},
    {'dt_code': 'ZONE 3 BLOCKED BY PICKUP', 'fault_code': 10001},
    {'dt_code': 'CONV ZONE 1 BLOCKED BY TCI', 'fault_code': 10001},
    {'dt_code': 'BLOCKED BY CONV ZONE 3', 'fault_code': 10001},
    {'dt_code': 'STARVED - VISION STA.', 'fault_code': 10002},
    {'dt_code': 'STARVED- STA 1', 'fault_code': 10003},
    {'dt_code': 'STARVED- STA 2', 'fault_code': 10004},
    {'dt_code': 'STARVED- STA 3', 'fault_code': 10005},
    {'dt_code': 'STARVED- STA 4', 'fault_code': 10006},
    {'dt_code': 'STARVED- STA 5', 'fault_code': 10007},
    {'dt_code': 'STARVED- STA 6', 'fault_code': 10008},
    {'dt_code': 'STARVED- STA 7', 'fault_code': 10009},
    {'dt_code': 'STARVED - UNLOAD STA', 'fault_code': 10010},
    {'dt_code': 'STA 11 BLOCKED BY CHRG STA', 'fault_code': 10101},
    {'dt_code': 'STA 41 BLOCKED - REPAIR/CV3', 'fault_code': 10101},
    {'dt_code': 'STA 31 BLOCKED BY REPAIR', 'fault_code': 10101},
    {'dt_code': 'STA 32 BLOCKED BY REPAIR', 'fault_code': 10102},
    {'dt_code': 'STA 42 BLOCKED BY REPAIR', 'fault_code': 10102},
    {'dt_code': 'STA 33 BLOCKED BY TCI', 'fault_code': 10103},
    {'dt_code': 'CHRG STA BLOCKED BY STA 24', 'fault_code': 10107},
    {'dt_code': 'CHRG STA BLOCKED BY STA 24', 'fault_code': 10110},
    {'dt_code': 'TCI BLOCKED - REPAIR / CV3', 'fault_code': 10110},
    {'dt_code': 'STA 24 BLOCKED BY STA 28', 'fault_code': 10114},
    {'dt_code': 'STA 56 BLOCKED BY PICKUP', 'fault_code': 10116},
    {'dt_code': 'WAITING ON PICKUP @ EOL', 'fault_code': 10117},
    {'dt_code': 'STA 28 BLOCKED BY TCI', 'fault_code': 10118},
    {'dt_code': 'CONV ZONE 1 BLOCKED BY TCI', 'fault_code': 10120},
    {'dt_code': 'CONV ZONE 1 STARVED BY AGC', 'fault_code': 10201},
    {'dt_code': 'ZONE 3 STARVED BY TCI', 'fault_code': 10201},
    {'dt_code': 'STARVED BY CONV ZONE 1', 'fault_code': 10201},
    {'dt_code': 'TCI ZONE STARVED', 'fault_code': 10202},
    {'dt_code': 'CONV ZONE 3 STARVED', 'fault_code': 10202},
    {'dt_code': 'CONV ZONE 1 STARVED', 'fault_code': 10202},
    {'dt_code': 'STA 11 STARVED BY AGC ZONE', 'fault_code': 10301},
    {'dt_code': 'STA 41 STARVED BY TCI', 'fault_code': 10301},
    {'dt_code': 'STA 31 STARVED BY CONV ZONE 1', 'fault_code': 10301},
    {'dt_code': 'STA 47 STARVED BY TCI', 'fault_code': 10307},
    {'dt_code': 'CHARGE STA STARVED BY TIPUP', 'fault_code': 10307},
    {'dt_code': 'STA 24 STARVED BY CHRG STA', 'fault_code': 10314},
    {'dt_code': 'STA 28 STARVED BY STA 24', 'fault_code': 10318},
    {'dt_code': 'BLOCKED - LOAD STA', 'fault_code': 11001},
    {'dt_code': 'BLOCKED - VISION STA', 'fault_code': 11002},
    {'dt_code': 'BLOCKED- STA 1', 'fault_code': 11003},
    {'dt_code': 'BLOCKED- STA 2', 'fault_code': 11004},
    {'dt_code': 'BLOCKED- STA 3', 'fault_code': 11005},
    {'dt_code': 'BLOCKED- STA 4', 'fault_code': 11006},
    {'dt_code': 'BLOCKED- STA 5', 'fault_code': 11007},
    {'dt_code': 'BLOCKED- STA 6', 'fault_code': 11008},
    {'dt_code': 'BLOCKED- STA 7', 'fault_code': 11009},
    {'dt_code': 'BLOCKED - UNLOAD STA', 'fault_code': 11010},
    {'dt_code': 'BLOCKED - MAINT. STA', 'fault_code': 11011},
    {'dt_code': 'ZONE DOWN - LOAD STA', 'fault_code': 12001},
    {'dt_code': 'HELP CALL - STA 11', 'fault_code': 12001},
    {'dt_code': 'HELP CALL - STA 47', 'fault_code': 12001},
    {'dt_code': 'HELP CALL - STA 40 TCI', 'fault_code': 12001},
    {'dt_code': 'HELP CALL - STA 51', 'fault_code': 12002},
    {'dt_code': 'HELP CALL - CHARGE STA', 'fault_code': 12002},
    {'dt_code': 'ZONE DOWN - VISION STA', 'fault_code': 12002},
    {'dt_code': 'ZONE DOWN - STA 1', 'fault_code': 12003},
    {'dt_code': 'HELP CALL - STA 24', 'fault_code': 12003},
    {'dt_code': 'HELP CALL - STA 55', 'fault_code': 12003},
    {'dt_code': 'HELP CALL - STA 28', 'fault_code': 12004},
    {'dt_code': 'ZONE DOWN - STA 2', 'fault_code': 12004},
    {'dt_code': 'ZONE DOWN - STA 2 SUB-ASM', 'fault_code': 12005},
    {'dt_code': 'ZONE DOWN - STA 4', 'fault_code': 12006},
    {'dt_code': 'ZONE DOWN - STA 5', 'fault_code': 12007},
    {'dt_code': 'ZONE DOWN - STA 6', 'fault_code': 12008},
    {'dt_code': 'ZONE DOWN - STA 7', 'fault_code': 12009},
    {'dt_code': 'ZONE DOWN - UNLOAD STA', 'fault_code': 12010},
    {'dt_code': 'ZONE DOWN - STA 3', 'fault_code': 12011},
    {'dt_code': 'ZONE DOWN - STA 4-5 SUB-ASM', 'fault_code': 12012},
    {'dt_code': 'NO UNIT AT POST FOAM ', 'fault_code': 12013},
    {'dt_code': 'BLOCKED BY CONVEYOR ZONE 1', 'fault_code': 12014},
    {'dt_code': 'BARCODE NOT VALID - LOAD STA', 'fault_code': 12016},
    {'dt_code': 'STA 11 ANDON PAST TAKT', 'fault_code': 12051},
    {'dt_code': 'STATION DOWN - STA 47', 'fault_code': 12051},
    {'dt_code': 'STA 40 TCI ANDON PAST TAKT', 'fault_code': 12051},
    {'dt_code': 'STATION DOWN - STA 51', 'fault_code': 12052},
    {'dt_code': 'CHRG STA ANDON PAST TAKT', 'fault_code': 12052},
    {'dt_code': 'STA 24 ANDON PAST TAKT', 'fault_code': 12053},
    {'dt_code': 'STATION DOWN - STA 55', 'fault_code': 12053},
    {'dt_code': 'STA 28 ANDON PAST TAKT', 'fault_code': 12054},
    {'dt_code': 'CYCLE STOP - STA 11', 'fault_code': 12101},
    {'dt_code': 'CYCLE STOP - STA 47', 'fault_code': 12101},
    {'dt_code': 'NOT COMPLETE - LOAD STA', 'fault_code': 12101},
    {'dt_code': 'CYCLE STOP - STA 40 TCI', 'fault_code': 12101},
    {'dt_code': 'NOT COMPLETE VISION STA', 'fault_code': 12102},
    {'dt_code': 'CYCLE STOP- STA 51', 'fault_code': 12102},
    {'dt_code': 'CYCLE STOP - CHARGE STA', 'fault_code': 12102},
    {'dt_code': 'CYCLE STOP - STA 24', 'fault_code': 12103},
    {'dt_code': 'CYCLE STOP - STA 55', 'fault_code': 12103},
    {'dt_code': 'STATION 1 NOT COMPLETE', 'fault_code': 12103},
    {'dt_code': 'STATION 2 NOT COMPLETE', 'fault_code': 12104},
    {'dt_code': 'CYCLE STOP - STA 28', 'fault_code': 12104},
    {'dt_code': 'STATION 3 NOT COMPLETE', 'fault_code': 12105},
    {'dt_code': 'STATION 4 NOT COMPLETE', 'fault_code': 12106},
    {'dt_code': 'STATION 5 NOT COMPLETE', 'fault_code': 12107},
    {'dt_code': 'STATION 6 NOT COMPLETE', 'fault_code': 12108},
    {'dt_code': 'STATION 7 NOT COMPLETE', 'fault_code': 12109},
    {'dt_code': 'BLOCKED - CONVEYOR ZONE 1', 'fault_code': 12110},
    {'dt_code': 'HELP CALL - LOAD STA', 'fault_code': 12201},
    {'dt_code': 'HELP CALL - VISION STA', 'fault_code': 12202},
    {'dt_code': 'HELP CALL - STA 1', 'fault_code': 12203},
    {'dt_code': 'HELP CALL - STA 2', 'fault_code': 12204},
    {'dt_code': 'HELP CALL - STA 2 SUB-ASM', 'fault_code': 12205},
    {'dt_code': 'HELP CALL - STA 4', 'fault_code': 12206},
    {'dt_code': 'HELP CALL - STA 5', 'fault_code': 12207},
    {'dt_code': 'HELP CALL - STA 6', 'fault_code': 12208},
    {'dt_code': 'HELP CALL - STA 7', 'fault_code': 12209},
    {'dt_code': 'HELP CALL - UNLOAD STA', 'fault_code': 12210},
    {'dt_code': 'HELP CALL - STA 3', 'fault_code': 12211},
    {'dt_code': 'HELP CALL - STA 4-5 SUB-ASM', 'fault_code': 12212},
    {'dt_code': 'EFLEX FAULT - LOAD STA', 'fault_code': 12301},
    {'dt_code': 'EFLEX FAULT - VISION STA', 'fault_code': 12302},
    {'dt_code': 'EFLEX FAULT- STA 1', 'fault_code': 12303},
    {'dt_code': 'EFLEX FAULT- STA 2', 'fault_code': 12304},
    {'dt_code': 'EFLEX FAULT- STA 3', 'fault_code': 12305},
    {'dt_code': 'EFLEX FAULT- STA 4', 'fault_code': 12306},
    {'dt_code': 'EFLEX FAULT- STA 5', 'fault_code': 12307},
    {'dt_code': 'EFLEX FAULT- STA 6', 'fault_code': 12308},
    {'dt_code': 'EFLEX FAULT- STA 7', 'fault_code': 12309},
    {'dt_code': 'SCHEDULED RUN - START LINE', 'fault_code': 12400},
    {'dt_code': 'NO SIGNAL - EFLEX LOAD', 'fault_code': 12401},
    {'dt_code': 'NO SIGNAL - EFLEX VISION STA', 'fault_code': 12402},
    {'dt_code': 'NO SIGNAL - EFLEX STA 1', 'fault_code': 12403},
    {'dt_code': 'NO SIGNAL - EFLEX STA 2', 'fault_code': 12404},
    {'dt_code': 'NO SIGNAL - EFLEX STA 3', 'fault_code': 12405},
    {'dt_code': 'NO SIGNAL - EFLEX STA 4', 'fault_code': 12406},
    {'dt_code': 'NO SIGNAL - EFLEX STA 5', 'fault_code': 12407},
    {'dt_code': 'NO SIGNAL - EFLEX STA 6', 'fault_code': 12408},
    {'dt_code': 'NO SIGNAL - EFLEX STA 7', 'fault_code': 12409},
    {'dt_code': 'NO SIGNAL - UNLOAD STA', 'fault_code': 12410},
    {'dt_code': 'NO SERIAL # AT LOAD STA', 'fault_code': 12420},
    {'dt_code': 'NO SERIAL # AT STA 1', 'fault_code': 12421},
    {'dt_code': 'NO SERIAL # AT STA 2', 'fault_code': 12422},
    {'dt_code': 'NO SERIAL # AT STA 3', 'fault_code': 12423},
    {'dt_code': 'NO SERIAL # AT STA 4', 'fault_code': 12424},
    {'dt_code': 'NO SERIAL # AT STA 5', 'fault_code': 12425},
    {'dt_code': 'NO SERIAL # AT STA 6', 'fault_code': 12426},
    {'dt_code': 'NO SERIAL # AT UNLOAD STA', 'fault_code': 12427},
    {'dt_code': 'STA 11 NOT COMPLETE', 'fault_code': 12501},
    {'dt_code': 'STA 47 NOT COMPLETE', 'fault_code': 12501},
    {'dt_code': 'REPAIR IN NOT CLEAR', 'fault_code': 12501},
    {'dt_code': 'REPAIR OUT NOT CLEAR', 'fault_code': 12502},
    {'dt_code': 'STA 51 NOT COMPLETE', 'fault_code': 12502},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12502},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12503},
    {'dt_code': 'STA 55 NOT COMPLETE', 'fault_code': 12503},
    {'dt_code': 'TCI STA 40 NOT COMPLETE', 'fault_code': 12503},
    {'dt_code': 'STA 56 NOT COMPLETE', 'fault_code': 12504},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12504},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12505},
    {'dt_code': 'REPAIR IN/OUT NOT COMPLETE', 'fault_code': 12505},
    {'dt_code': 'STA 24 NOT COMPLETE', 'fault_code': 12506},
    {'dt_code': 'STA 28 NOT COMPLETE', 'fault_code': 12507},
    {'dt_code': 'STA 11 NOT COMPLETE', 'fault_code': 12601},
    {'dt_code': 'STA 47 NOT COMPLETE', 'fault_code': 12601},
    {'dt_code': 'STA 31 NOT COMPLETE', 'fault_code': 12601},
    {'dt_code': 'STA 32 NOT COMPLETE', 'fault_code': 12602},
    {'dt_code': 'STA 51 NOT COMPLETE', 'fault_code': 12602},
    {'dt_code': 'CHRG STA NOT COMPLETE', 'fault_code': 12602},
    {'dt_code': 'STA 24 NOT COMPLETE', 'fault_code': 12603},
    {'dt_code': 'STA 55 NOT COMPLETE', 'fault_code': 12603},
    {'dt_code': 'STA 33 NOT COMPLETE', 'fault_code': 12603},
    {'dt_code': 'STA 40 TCI OVERTRAVELED', 'fault_code': 12604},
    {'dt_code': 'STA 57 NOT COMPLETE', 'fault_code': 12604},
    {'dt_code': 'STA 28 NOT COMPLETE', 'fault_code': 12604},
    {'dt_code': 'REPAIR IN/OUT NOT COMPLETE', 'fault_code': 12605},
    {'dt_code': 'WAITING ON AGC AT UNLOAD', 'fault_code': 12701},
    {'dt_code': 'STOP-Stn 24 Warning Label Scan', 'fault_code': 14001},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15001},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15001},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15001},
    {'dt_code': 'ESTOP - ZONE 1 OR ZONE 3', 'fault_code': 15002},
    {'dt_code': 'ESTOP - CONV ZONE 2', 'fault_code': 15002},
    {'dt_code': 'ESTOP - STA 11', 'fault_code': 15011},
    {'dt_code': 'ESTOP - STA 41', 'fault_code': 15011},
    {'dt_code': 'ESTOP - STA 34', 'fault_code': 15011},
    {'dt_code': 'ESTOP - STA 36', 'fault_code': 15012},
    {'dt_code': 'ESTOP - STA 47', 'fault_code': 15012},
    {'dt_code': 'ESTOP - CHARGE STA SOUTH', 'fault_code': 15012},
    {'dt_code': 'ESTOP - CHARGE STA NORTH', 'fault_code': 15013},
    {'dt_code': 'ESTOP - STA 52', 'fault_code': 15013},
    {'dt_code': 'ESTOP - STA 57', 'fault_code': 15014},
    {'dt_code': 'ESTOP - STA 24', 'fault_code': 15014},
    {'dt_code': 'ESTOP - STA 60', 'fault_code': 15015}
]

New = [
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 17},
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 18},
    {'dt_code': 'SCHEDULED RUN (OFF AT PANEL)', 'fault_code': 19},
    {'dt_code': 'Conveyor VFD 1 Faulted', 'fault_code': 1001},
    {'dt_code': 'Conveyor VFD 1 Faulted', 'fault_code': 1002},
    {'dt_code': 'PROCESS FAULT - AGC 1', 'fault_code': 1003},
    {'dt_code': 'PROCESS FAULT - AGC 2', 'fault_code': 1004},
    {'dt_code': 'PROCESS FAULT - AGC 3', 'fault_code': 1005},
    {'dt_code': 'PROCESS FAULT - AGC 4', 'fault_code': 1006},
    {'dt_code': 'PROCESS FAULT - AGC 5', 'fault_code': 1007},
    {'dt_code': 'PROCESS FAULT - AGC 6', 'fault_code': 1008},
    {'dt_code': 'PROCESS FAULT - AGC 7', 'fault_code': 1009},
    {'dt_code': 'PROCESS FAULT - AGC 8', 'fault_code': 1010},
    {'dt_code': 'PROCESS FAULT - AGC 9', 'fault_code': 1011},
    {'dt_code': 'PROCESS FAULT - AGC 10', 'fault_code': 1012},
    {'dt_code': 'PROCESS FAULT - AGC 11', 'fault_code': 1013},
    {'dt_code': 'PROCESS FAULT - AGC 12', 'fault_code': 1014},
    {'dt_code': 'PROCESS FAULT - AGC 13', 'fault_code': 1015},
    {'dt_code': 'PROCESS FAULT - AGC 14', 'fault_code': 1016},
    {'dt_code': 'INVALID RUN MODE SELECTED', 'fault_code': 1017},
    {'dt_code': 'ELEC FAULT - STA 41', 'fault_code': 1018},
    {'dt_code': 'ELEC FAULT - STA 11', 'fault_code': 1019},
    {'dt_code': 'ELEC FAULT - STA 31', 'fault_code': 1020},
    {'dt_code': 'ELEC FAULT - STA 32', 'fault_code': 1021},
    {'dt_code': 'ELEC FAULT - STA 12', 'fault_code': 1022},
    {'dt_code': 'ELEC FAULT - STA 42', 'fault_code': 1023},
    {'dt_code': 'ELEC FAULT - STA 43', 'fault_code': 1024},
    {'dt_code': 'ELEC FAULT - STA 13', 'fault_code': 1025},
    {'dt_code': 'ELEC FAULT - STA 33', 'fault_code': 1026},
    {'dt_code': 'ELEC FAULT - STA 34', 'fault_code': 1027},
    {'dt_code': 'ELEC FAULT - STA 14', 'fault_code': 1028},
    {'dt_code': 'ELEC FAULT - STA 44', 'fault_code': 1029},
    {'dt_code': 'ELEC FAULT - STA 45', 'fault_code': 1030},
    {'dt_code': 'ELEC FAULT - STA 15', 'fault_code': 1031},
    {'dt_code': 'ELEC FAULT - STA 35', 'fault_code': 1032},
    {'dt_code': 'ELEC FAULT - STA 36', 'fault_code': 1033},
    {'dt_code': 'ELEC FAULT - STA 16', 'fault_code': 1034},
    {'dt_code': 'ELEC FAULT - STA 46', 'fault_code': 1035},
    {'dt_code': 'ELEC FAULT - STA 47', 'fault_code': 1036},
    {'dt_code': 'ELEC FAULT - STA 17', 'fault_code': 1037},
    {'dt_code': 'ELEC FAULT - STA 37', 'fault_code': 1038},
    {'dt_code': 'ELEC FAULT - STA 38', 'fault_code': 1039},
    {'dt_code': 'ELEC FAULT - STA 18', 'fault_code': 1040},
    {'dt_code': 'ELEC FAULT - STA 48', 'fault_code': 1041},
    {'dt_code': 'ELEC FAULT - STA 49', 'fault_code': 1042},
    {'dt_code': 'ELEC FAULT - STA 19', 'fault_code': 1043},
    {'dt_code': 'ELEC FAULT - STA 39', 'fault_code': 1044},
    {'dt_code': 'ELEC FAULT - STA 40', 'fault_code': 1045},
    {'dt_code': 'ELEC FAULT - STA 20', 'fault_code': 1046},
    {'dt_code': 'ELEC FAULT - STA 50', 'fault_code': 1047},
    {'dt_code': 'ELEC FAULT - STA 51', 'fault_code': 1048},
    {'dt_code': 'ELEC FAULT - STA 21', 'fault_code': 1049},
    {'dt_code': 'ELEC FAULT - REPAIR IN', 'fault_code': 1050},
    {'dt_code': 'ELEC FAULT - REPAIR OUT', 'fault_code': 1051},
    {'dt_code': 'ELEC FAULT - STA 22', 'fault_code': 1052},
    {'dt_code': 'ELEC FAULT - STA 52', 'fault_code': 1053},
    {'dt_code': 'ELEC FAULT - STA 53', 'fault_code': 1054},
    {'dt_code': 'ELEC FAULT - STA 23', 'fault_code': 1055},
    {'dt_code': 'ELEC FAULT - TCI', 'fault_code': 1056},
    {'dt_code': 'ELEC FAULT - STA 24', 'fault_code': 1057},
    {'dt_code': 'ELEC FAULT - STA 54', 'fault_code': 1058},
    {'dt_code': 'ELEC FAULT - STA 55', 'fault_code': 1059},
    {'dt_code': 'ELEC FAULT - STA 25', 'fault_code': 1060},
    {'dt_code': 'ELEC FAULT - STA 26', 'fault_code': 1061},
    {'dt_code': 'ELEC FAULT - STA 56', 'fault_code': 1062},
    {'dt_code': 'ELEC FAULT - STA 57', 'fault_code': 1063},
    {'dt_code': 'ELEC FAULT - STA 27', 'fault_code': 1064},
    {'dt_code': 'ELEC FAULT - STA 28', 'fault_code': 1065},
    {'dt_code': 'ELEC FAULT - STA 58', 'fault_code': 1066},
    {'dt_code': 'ELEC FAULT - STA 59', 'fault_code': 1067},
    {'dt_code': 'ELEC FAULT - STA 29', 'fault_code': 1068},
    {'dt_code': 'ELEC FAULT - STA 30', 'fault_code': 1069},
    {'dt_code': 'ELEC FAULT - STA 60', 'fault_code': 1070},
    {'dt_code': 'ELEC FAULT - REPAIR IN/OUT', 'fault_code': 1071},
    {'dt_code': 'PROCESS FAULT - LOAD STA', 'fault_code': 1072},
    {'dt_code': 'PROCESS FAULT - VISION STA', 'fault_code': 1073},
    {'dt_code': 'PROCESS FAULT - STA 1', 'fault_code': 1074},
    {'dt_code': 'PROCESS FAULT - STA 2', 'fault_code': 1075},
    {'dt_code': 'PROCESS FAULT - STA 3', 'fault_code': 1076},
    {'dt_code': 'PROCESS FAULT - STA 4', 'fault_code': 1077},
    {'dt_code': 'PROCESS FAULT - STA 5', 'fault_code': 1078},
    {'dt_code': 'PROCESS FAULT - STA 6', 'fault_code': 1079},
    {'dt_code': 'PROCESS FAULT - STA 7', 'fault_code': 1080},
    {'dt_code': 'PROCESS FAULT - UNLOAD', 'fault_code': 1081},
    {'dt_code': 'PROCESS FAULT - LOAD HLDBACK', 'fault_code': 1082},
    {'dt_code': 'PROCESS FAULT - VISION HLDBACK', 'fault_code': 1083},
    {'dt_code': 'NO PART AT STA 1 HOLDBACK', 'fault_code': 1084},
    {'dt_code': 'PROCESS FAULT - UNLOAD HLDBACK', 'fault_code': 1085},
    {'dt_code': 'ESTOP - AGC 1', 'fault_code': 1086},
    {'dt_code': 'ESTOP - AGC 2', 'fault_code': 1087},
    {'dt_code': 'ESTOP - AGC 3', 'fault_code': 1088},
    {'dt_code': 'ESTOP - AGC 4', 'fault_code': 1089},
    {'dt_code': 'ESTOP - AGC 5', 'fault_code': 1090},
    {'dt_code': 'ESTOP - AGC 6', 'fault_code': 1091},
    {'dt_code': 'ESTOP - AGC 7', 'fault_code': 1092},
    {'dt_code': 'ESTOP - AGC 8', 'fault_code': 1093},
    {'dt_code': 'ESTOP - AGC 9', 'fault_code': 1094},
    {'dt_code': 'ESTOP - AGC 10', 'fault_code': 1095},
    {'dt_code': 'ESTOP - AGC 11', 'fault_code': 1096},
    {'dt_code': 'ESTOP - AGC 12', 'fault_code': 1097},
    {'dt_code': 'ESTOP - AGC 13', 'fault_code': 1098},
    {'dt_code': 'ESTOP - AGC 14', 'fault_code': 1099},
    {'dt_code': 'SEND AGC 1 TO MAINT', 'fault_code': 1100},
    {'dt_code': 'SEND AGC 2 TO MAINT', 'fault_code': 1101},
    {'dt_code': 'SEND AGC 3 TO MAINT', 'fault_code': 1102},
    {'dt_code': 'SEND AGC 4 TO MAINT', 'fault_code': 1103},
    {'dt_code': 'SEND AGC 5 TO MAINT', 'fault_code': 1104},
    {'dt_code': 'SEND AGC 6 TO MAINT', 'fault_code': 1105},
    {'dt_code': 'SEND AGC 7 TO MAINT', 'fault_code': 1106},
    {'dt_code': 'SEND AGC 8 TO MAINT', 'fault_code': 1107},
    {'dt_code': 'SEND AGC 9 TO MAINT', 'fault_code': 1108},
    {'dt_code': 'SEND AGC 10 TO MAINT', 'fault_code': 1109},
    {'dt_code': 'SEND AGC 11 TO MAINT', 'fault_code': 1110},
    {'dt_code': 'SEND AGC 12 TO MAINT', 'fault_code': 1111},
    {'dt_code': 'SEND AGC 13 TO MAINT', 'fault_code': 1112},
    {'dt_code': 'SEND AGC 14 TO MAINT', 'fault_code': 1113},
    {'dt_code': 'BLOCKED - AGC 1', 'fault_code': 2001},
    {'dt_code': 'BLOCKED - AGC 2', 'fault_code': 2002},
    {'dt_code': 'BLOCKED - AGC 3', 'fault_code': 2003},
    {'dt_code': 'BLOCKED - AGC 4', 'fault_code': 2004},
    {'dt_code': 'BLOCKED - AGC 5', 'fault_code': 2005},
    {'dt_code': 'BLOCKED - AGC 6', 'fault_code': 2006},
    {'dt_code': 'BLOCKED - AGC 7', 'fault_code': 2007},
    {'dt_code': 'BLOCKED - AGC 8', 'fault_code': 2008},
    {'dt_code': 'BLOCKED - AGC 9', 'fault_code': 2009},
    {'dt_code': 'BLOCKED - AGC 10', 'fault_code': 2010},
    {'dt_code': 'BLOCKED - AGC 11', 'fault_code': 2011},
    {'dt_code': 'BLOCKED - AGC 12', 'fault_code': 2012},
    {'dt_code': 'BLOCKED - AGC 13', 'fault_code': 2013},
    {'dt_code': 'BLOCKED - AGC 14', 'fault_code': 2014},
    {'dt_code': 'MECH FAULT - STA 41', 'fault_code': 2015},
    {'dt_code': 'MECH FAULT - STA 11', 'fault_code': 2016},
    {'dt_code': 'MECH FAULT - STA 31', 'fault_code': 2017},
    {'dt_code': 'MECH FAULT - STA 32', 'fault_code': 2018},
    {'dt_code': 'MECH FAULT - STA 12', 'fault_code': 2019},
    {'dt_code': 'MECH FAULT - STA 42', 'fault_code': 2020},
    {'dt_code': 'MECH FAULT - STA 43', 'fault_code': 2021},
    {'dt_code': 'MECH FAULT - STA 13', 'fault_code': 2022},
    {'dt_code': 'MECH FAULT - STA 33', 'fault_code': 2023},
    {'dt_code': 'MECH FAULT - STA 34', 'fault_code': 2024},
    {'dt_code': 'MECH FAULT - STA 14', 'fault_code': 2025},
    {'dt_code': 'MECH FAULT - STA 44', 'fault_code': 2026},
    {'dt_code': 'MECH FAULT - STA 45', 'fault_code': 2027},
    {'dt_code': 'MECH FAULT - STA 15', 'fault_code': 2028},
    {'dt_code': 'MECH FAULT - STA 35', 'fault_code': 2029},
    {'dt_code': 'MECH FAULT - STA 36', 'fault_code': 2030},
    {'dt_code': 'MECH FAULT - STA 16', 'fault_code': 2031},
    {'dt_code': 'MECH FAULT - STA 46', 'fault_code': 2032},
    {'dt_code': 'MECH FAULT - STA 47', 'fault_code': 2033},
    {'dt_code': 'MECH FAULT - STA 17', 'fault_code': 2034},
    {'dt_code': 'MECH FAULT - STA 37', 'fault_code': 2035},
    {'dt_code': 'MECH FAULT - STA 38', 'fault_code': 2036},
    {'dt_code': 'MECH FAULT - STA 18', 'fault_code': 2037},
    {'dt_code': 'MECH FAULT - STA 48', 'fault_code': 2038},
    {'dt_code': 'MECH FAULT - STA 49', 'fault_code': 2039},
    {'dt_code': 'MECH FAULT - STA 19', 'fault_code': 2040},
    {'dt_code': 'MECH FAULT - STA 39', 'fault_code': 2041},
    {'dt_code': 'MECH FAULT - STA 40', 'fault_code': 2042},
    {'dt_code': 'MECH FAULT - STA 20', 'fault_code': 2043},
    {'dt_code': 'MECH FAULT - STA 50', 'fault_code': 2044},
    {'dt_code': 'MECH FAULT - STA 51', 'fault_code': 2045},
    {'dt_code': 'MECH FAULT - STA 21', 'fault_code': 2046},
    {'dt_code': 'MECH FAULT - REPAIR IN', 'fault_code': 2047},
    {'dt_code': 'MECH FAULT - REPAIR OUT', 'fault_code': 2048},
    {'dt_code': 'MECH FAULT - STA 22', 'fault_code': 2049},
    {'dt_code': 'MECH FAULT - STA 52', 'fault_code': 2050},
    {'dt_code': 'MECH FAULT - STA 53', 'fault_code': 2051},
    {'dt_code': 'MECH FAULT - STA 23', 'fault_code': 2052},
    {'dt_code': 'MECH FAULT TCI', 'fault_code': 2053},
    {'dt_code': 'MECH FAULT - STA 24', 'fault_code': 2054},
    {'dt_code': 'MECH FAULT - STA 54', 'fault_code': 2055},
    {'dt_code': 'MECH FAULT - STA 55', 'fault_code': 2056},
    {'dt_code': 'MECH FAULT - STA 25', 'fault_code': 2057},
    {'dt_code': 'MECH FAULT - STA 26', 'fault_code': 2058},
    {'dt_code': 'MECH FAULT - STA 56', 'fault_code': 2059},
    {'dt_code': 'MECH FAULT - STA 57', 'fault_code': 2060},
    {'dt_code': 'MECH FAULT - STA 27', 'fault_code': 2061},
    {'dt_code': 'MECH FAULT - STA 28', 'fault_code': 2062},
    {'dt_code': 'MECH FAULT - STA 58', 'fault_code': 2063},
    {'dt_code': 'MECH FAULT - STA 59', 'fault_code': 2064},
    {'dt_code': 'MECH FAULT - STA 29', 'fault_code': 2065},
    {'dt_code': 'MECH FAULT - STA 30', 'fault_code': 2066},
    {'dt_code': 'MECH FAULT - STA 60', 'fault_code': 2067},
    {'dt_code': 'MECH FAULT - REPAIR IN/OUT', 'fault_code': 2068},
    {'dt_code': 'STA 11 SAFETY SCANNER', 'fault_code': 2069},
    {'dt_code': 'STA 24 SAFETY SCANNER', 'fault_code': 2070},
    {'dt_code': 'STA 28 SAFETY SCANNER', 'fault_code': 2071},
    {'dt_code': 'COM FAULT - CONV ZONE 1', 'fault_code': 5001},
    {'dt_code': 'COM FAULT - CONV ZONE 3', 'fault_code': 5002},
    {'dt_code': 'COM FAULT - AGC 1', 'fault_code': 5003},
    {'dt_code': 'COM FAULT - CONV ZONE 2', 'fault_code': 5004},
    {'dt_code': 'COM FAULT - AGC 2', 'fault_code': 5005},
    {'dt_code': 'COM FAULT - AGC 3', 'fault_code': 5006},
    {'dt_code': 'COM FAULT - AGC 4', 'fault_code': 5007},
    {'dt_code': 'COM FAULT - AGC 5', 'fault_code': 5008},
    {'dt_code': 'COM FAULT - AGC 6', 'fault_code': 5009},
    {'dt_code': 'COM FAULT - AGC 7', 'fault_code': 5010},
    {'dt_code': 'COM FAULT - AGC 8', 'fault_code': 5011},
    {'dt_code': 'COM FAULT - AGC 9', 'fault_code': 5012},
    {'dt_code': 'COM FAULT - AGC 10', 'fault_code': 5013},
    {'dt_code': 'COM FAULT - AGC 11', 'fault_code': 5014},
    {'dt_code': 'COM FAULT - AGC 12', 'fault_code': 5015},
    {'dt_code': 'COM FAULT - AGC 13', 'fault_code': 5016},
    {'dt_code': 'COM FAULT - AGC 14', 'fault_code': 5017},
    {'dt_code': 'COM FAULT - PLC CARDS', 'fault_code': 5018},
    {'dt_code': 'COM FAULT - L51POSTFOAM PLC', 'fault_code': 5019},
    {'dt_code': 'COM FAULT - L52CONV PLC', 'fault_code': 5020},
    {'dt_code': 'COM FAULT - EFLEX', 'fault_code': 5021},
    {'dt_code': 'COM FAULT - SAM', 'fault_code': 5022},
    {'dt_code': 'COM FAULT - EFLEX MODULE', 'fault_code': 5023},
    {'dt_code': 'STARVED- LOAD STA.', 'fault_code': 10001},
    {'dt_code': 'ZONE 3 BLOCKED BY PICKUP', 'fault_code': 10002},
    {'dt_code': 'CONV ZONE 1 BLOCKED BY TCI', 'fault_code': 10003},
    {'dt_code': 'BLOCKED BY CONV ZONE 3', 'fault_code': 10004},
    {'dt_code': 'STARVED - VISION STA.', 'fault_code': 10005},
    {'dt_code': 'STARVED- STA 1', 'fault_code': 10006},
    {'dt_code': 'STARVED- STA 2', 'fault_code': 10007},
    {'dt_code': 'STARVED- STA 3', 'fault_code': 10008},
    {'dt_code': 'STARVED- STA 4', 'fault_code': 10009},
    {'dt_code': 'STARVED- STA 5', 'fault_code': 10010},
    {'dt_code': 'STARVED- STA 6', 'fault_code': 10011},
    {'dt_code': 'STARVED- STA 7', 'fault_code': 10012},
    {'dt_code': 'STARVED - UNLOAD STA', 'fault_code': 10013},
    {'dt_code': 'STA 11 BLOCKED BY CHRG STA', 'fault_code': 10014},
    {'dt_code': 'STA 41 BLOCKED - REPAIR/CV3', 'fault_code': 10015},
    {'dt_code': 'STA 31 BLOCKED BY REPAIR', 'fault_code': 10016},
    {'dt_code': 'STA 32 BLOCKED BY REPAIR', 'fault_code': 10017},
    {'dt_code': 'STA 42 BLOCKED BY REPAIR', 'fault_code': 10018},
    {'dt_code': 'STA 33 BLOCKED BY TCI', 'fault_code': 10019},
    {'dt_code': 'CHRG STA BLOCKED BY STA 24', 'fault_code': 10020},
    {'dt_code': 'CHRG STA BLOCKED BY STA 24', 'fault_code': 10021},
    {'dt_code': 'TCI BLOCKED - REPAIR / CV3', 'fault_code': 10022},
    {'dt_code': 'STA 24 BLOCKED BY STA 28', 'fault_code': 10023},
    {'dt_code': 'STA 56 BLOCKED BY PICKUP', 'fault_code': 10024},
    {'dt_code': 'WAITING ON PICKUP @ EOL', 'fault_code': 10025},
    {'dt_code': 'STA 28 BLOCKED BY TCI', 'fault_code': 10026},
    {'dt_code': 'CONV ZONE 1 BLOCKED BY TCI', 'fault_code': 10027},
    {'dt_code': 'CONV ZONE 1 STARVED BY AGC', 'fault_code': 10028},
    {'dt_code': 'ZONE 3 STARVED BY TCI', 'fault_code': 10029},
    {'dt_code': 'STARVED BY CONV ZONE 1', 'fault_code': 10030},
    {'dt_code': 'TCI ZONE STARVED', 'fault_code': 10031},
    {'dt_code': 'CONV ZONE 3 STARVED', 'fault_code': 10032},
    {'dt_code': 'CONV ZONE 1 STARVED', 'fault_code': 10033},
    {'dt_code': 'STA 11 STARVED BY AGC ZONE', 'fault_code': 10034},
    {'dt_code': 'STA 41 STARVED BY TCI', 'fault_code': 10035},
    {'dt_code': 'STA 31 STARVED BY CONV ZONE 1', 'fault_code': 10036},
    {'dt_code': 'STA 47 STARVED BY TCI', 'fault_code': 10037},
    {'dt_code': 'CHARGE STA STARVED BY TIPUP', 'fault_code': 10038},
    {'dt_code': 'STA 24 STARVED BY CHRG STA', 'fault_code': 10039},
    {'dt_code': 'STA 28 STARVED BY STA 24', 'fault_code': 10040},
    {'dt_code': 'BLOCKED - LOAD STA', 'fault_code': 11001},
    {'dt_code': 'BLOCKED - VISION STA', 'fault_code': 11002},
    {'dt_code': 'BLOCKED- STA 1', 'fault_code': 11003},
    {'dt_code': 'BLOCKED- STA 2', 'fault_code': 11004},
    {'dt_code': 'BLOCKED- STA 3', 'fault_code': 11005},
    {'dt_code': 'BLOCKED- STA 4', 'fault_code': 11006},
    {'dt_code': 'BLOCKED- STA 5', 'fault_code': 11007},
    {'dt_code': 'BLOCKED- STA 6', 'fault_code': 11008},
    {'dt_code': 'BLOCKED- STA 7', 'fault_code': 11009},
    {'dt_code': 'BLOCKED - UNLOAD STA', 'fault_code': 11010},
    {'dt_code': 'BLOCKED - MAINT. STA', 'fault_code': 11011},
    {'dt_code': 'ZONE DOWN - LOAD STA', 'fault_code': 12001},
    {'dt_code': 'HELP CALL - STA 11', 'fault_code': 12002},
    {'dt_code': 'HELP CALL - STA 47', 'fault_code': 12003},
    {'dt_code': 'HELP CALL - STA 40 TCI', 'fault_code': 12004},
    {'dt_code': 'HELP CALL - STA 51', 'fault_code': 12005},
    {'dt_code': 'HELP CALL - CHARGE STA', 'fault_code': 12006},
    {'dt_code': 'ZONE DOWN - VISION STA', 'fault_code': 12007},
    {'dt_code': 'ZONE DOWN - STA 1', 'fault_code': 12008},
    {'dt_code': 'HELP CALL - STA 24', 'fault_code': 12009},
    {'dt_code': 'HELP CALL - STA 55', 'fault_code': 12010},
    {'dt_code': 'HELP CALL - STA 28', 'fault_code': 12011},
    {'dt_code': 'ZONE DOWN - STA 2', 'fault_code': 12012},
    {'dt_code': 'ZONE DOWN - STA 2 SUB-ASM', 'fault_code': 12013},
    {'dt_code': 'ZONE DOWN - STA 4', 'fault_code': 12014},
    {'dt_code': 'ZONE DOWN - STA 5', 'fault_code': 12015},
    {'dt_code': 'ZONE DOWN - STA 6', 'fault_code': 12016},
    {'dt_code': 'ZONE DOWN - STA 7', 'fault_code': 12017},
    {'dt_code': 'ZONE DOWN - UNLOAD STA', 'fault_code': 12018},
    {'dt_code': 'ZONE DOWN - STA 3', 'fault_code': 12019},
    {'dt_code': 'ZONE DOWN - STA 4-5 SUB-ASM', 'fault_code': 12020},
    {'dt_code': 'NO UNIT AT POST FOAM ', 'fault_code': 12021},
    {'dt_code': 'BLOCKED BY CONVEYOR ZONE 1', 'fault_code': 12022},
    {'dt_code': 'BARCODE NOT VALID - LOAD STA', 'fault_code': 12023},
    {'dt_code': 'STA 11 ANDON PAST TAKT', 'fault_code': 12024},
    {'dt_code': 'STATION DOWN - STA 47', 'fault_code': 12025},
    {'dt_code': 'STA 40 TCI ANDON PAST TAKT', 'fault_code': 12026},
    {'dt_code': 'STATION DOWN - STA 51', 'fault_code': 12027},
    {'dt_code': 'CHRG STA ANDON PAST TAKT', 'fault_code': 12028},
    {'dt_code': 'STA 24 ANDON PAST TAKT', 'fault_code': 12029},
    {'dt_code': 'STATION DOWN - STA 55', 'fault_code': 12030},
    {'dt_code': 'STA 28 ANDON PAST TAKT', 'fault_code': 12031},
    {'dt_code': 'CYCLE STOP - STA 11', 'fault_code': 12032},
    {'dt_code': 'CYCLE STOP - STA 47', 'fault_code': 12033},
    {'dt_code': 'NOT COMPLETE - LOAD STA', 'fault_code': 12034},
    {'dt_code': 'CYCLE STOP - STA 40 TCI', 'fault_code': 12035},
    {'dt_code': 'NOT COMPLETE VISION STA', 'fault_code': 12036},
    {'dt_code': 'CYCLE STOP- STA 51', 'fault_code': 12037},
    {'dt_code': 'CYCLE STOP - CHARGE STA', 'fault_code': 12038},
    {'dt_code': 'CYCLE STOP - STA 24', 'fault_code': 12039},
    {'dt_code': 'CYCLE STOP - STA 55', 'fault_code': 12040},
    {'dt_code': 'STATION 1 NOT COMPLETE', 'fault_code': 12041},
    {'dt_code': 'STATION 2 NOT COMPLETE', 'fault_code': 12042},
    {'dt_code': 'CYCLE STOP - STA 28', 'fault_code': 12043},
    {'dt_code': 'STATION 3 NOT COMPLETE', 'fault_code': 12044},
    {'dt_code': 'STATION 4 NOT COMPLETE', 'fault_code': 12045},
    {'dt_code': 'STATION 5 NOT COMPLETE', 'fault_code': 12046},
    {'dt_code': 'STATION 6 NOT COMPLETE', 'fault_code': 12047},
    {'dt_code': 'STATION 7 NOT COMPLETE', 'fault_code': 12048},
    {'dt_code': 'BLOCKED - CONVEYOR ZONE 1', 'fault_code': 12049},
    {'dt_code': 'HELP CALL - LOAD STA', 'fault_code': 12050},
    {'dt_code': 'HELP CALL - VISION STA', 'fault_code': 12051},
    {'dt_code': 'HELP CALL - STA 1', 'fault_code': 12052},
    {'dt_code': 'HELP CALL - STA 2', 'fault_code': 12053},
    {'dt_code': 'HELP CALL - STA 2 SUB-ASM', 'fault_code': 12054},
    {'dt_code': 'HELP CALL - STA 4', 'fault_code': 12055},
    {'dt_code': 'HELP CALL - STA 5', 'fault_code': 12056},
    {'dt_code': 'HELP CALL - STA 6', 'fault_code': 12057},
    {'dt_code': 'HELP CALL - STA 7', 'fault_code': 12058},
    {'dt_code': 'HELP CALL - UNLOAD STA', 'fault_code': 12059},
    {'dt_code': 'HELP CALL - STA 3', 'fault_code': 12060},
    {'dt_code': 'HELP CALL - STA 4-5 SUB-ASM', 'fault_code': 12061},
    {'dt_code': 'EFLEX FAULT - LOAD STA', 'fault_code': 12062},
    {'dt_code': 'EFLEX FAULT - VISION STA', 'fault_code': 12063},
    {'dt_code': 'EFLEX FAULT- STA 1', 'fault_code': 12064},
    {'dt_code': 'EFLEX FAULT- STA 2', 'fault_code': 12065},
    {'dt_code': 'EFLEX FAULT- STA 3', 'fault_code': 12066},
    {'dt_code': 'EFLEX FAULT- STA 4', 'fault_code': 12067},
    {'dt_code': 'EFLEX FAULT- STA 5', 'fault_code': 12068},
    {'dt_code': 'EFLEX FAULT- STA 6', 'fault_code': 12069},
    {'dt_code': 'EFLEX FAULT- STA 7', 'fault_code': 12070},
    {'dt_code': 'SCHEDULED RUN - START LINE', 'fault_code': 12071},
    {'dt_code': 'NO SIGNAL - EFLEX LOAD', 'fault_code': 12072},
    {'dt_code': 'NO SIGNAL - EFLEX VISION STA', 'fault_code': 12073},
    {'dt_code': 'NO SIGNAL - EFLEX STA 1', 'fault_code': 12074},
    {'dt_code': 'NO SIGNAL - EFLEX STA 2', 'fault_code': 12075},
    {'dt_code': 'NO SIGNAL - EFLEX STA 3', 'fault_code': 12076},
    {'dt_code': 'NO SIGNAL - EFLEX STA 4', 'fault_code': 12077},
    {'dt_code': 'NO SIGNAL - EFLEX STA 5', 'fault_code': 12078},
    {'dt_code': 'NO SIGNAL - EFLEX STA 6', 'fault_code': 12079},
    {'dt_code': 'NO SIGNAL - EFLEX STA 7', 'fault_code': 12080},
    {'dt_code': 'NO SIGNAL - UNLOAD STA', 'fault_code': 12081},
    {'dt_code': 'NO SERIAL # AT LOAD STA', 'fault_code': 12082},
    {'dt_code': 'NO SERIAL # AT STA 1', 'fault_code': 12083},
    {'dt_code': 'NO SERIAL # AT STA 2', 'fault_code': 12084},
    {'dt_code': 'NO SERIAL # AT STA 3', 'fault_code': 12085},
    {'dt_code': 'NO SERIAL # AT STA 4', 'fault_code': 12086},
    {'dt_code': 'NO SERIAL # AT STA 5', 'fault_code': 12087},
    {'dt_code': 'NO SERIAL # AT STA 6', 'fault_code': 12088},
    {'dt_code': 'NO SERIAL # AT UNLOAD STA', 'fault_code': 12089},
    {'dt_code': 'STA 11 NOT COMPLETE', 'fault_code': 12090},
    {'dt_code': 'STA 47 NOT COMPLETE', 'fault_code': 12091},
    {'dt_code': 'REPAIR IN NOT CLEAR', 'fault_code': 12092},
    {'dt_code': 'REPAIR OUT NOT CLEAR', 'fault_code': 12093},
    {'dt_code': 'STA 51 NOT COMPLETE', 'fault_code': 12094},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12095},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12096},
    {'dt_code': 'STA 55 NOT COMPLETE', 'fault_code': 12097},
    {'dt_code': 'TCI STA 40 NOT COMPLETE', 'fault_code': 12098},
    {'dt_code': 'STA 56 NOT COMPLETE', 'fault_code': 12099},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12100},
    {'dt_code': 'CHARGE STA NOT COMPLETE', 'fault_code': 12101},
    {'dt_code': 'REPAIR IN/OUT NOT COMPLETE', 'fault_code': 12102},
    {'dt_code': 'STA 24 NOT COMPLETE', 'fault_code': 12103},
    {'dt_code': 'STA 28 NOT COMPLETE', 'fault_code': 12104},
    {'dt_code': 'STA 11 NOT COMPLETE', 'fault_code': 12105},
    {'dt_code': 'STA 47 NOT COMPLETE', 'fault_code': 12106},
    {'dt_code': 'STA 31 NOT COMPLETE', 'fault_code': 12107},
    {'dt_code': 'STA 32 NOT COMPLETE', 'fault_code': 12108},
    {'dt_code': 'STA 51 NOT COMPLETE', 'fault_code': 12109},
    {'dt_code': 'CHRG STA NOT COMPLETE', 'fault_code': 12110},
    {'dt_code': 'STA 24 NOT COMPLETE', 'fault_code': 12111},
    {'dt_code': 'STA 55 NOT COMPLETE', 'fault_code': 12112},
    {'dt_code': 'STA 33 NOT COMPLETE', 'fault_code': 12113},
    {'dt_code': 'STA 40 TCI OVERTRAVELED', 'fault_code': 12114},
    {'dt_code': 'STA 57 NOT COMPLETE', 'fault_code': 12115},
    {'dt_code': 'STA 28 NOT COMPLETE', 'fault_code': 12116},
    {'dt_code': 'REPAIR IN/OUT NOT COMPLETE', 'fault_code': 12117},
    {'dt_code': 'WAITING ON AGC AT UNLOAD', 'fault_code': 12118},
    {'dt_code': 'STOP-Stn 24 Warning Label Scan', 'fault_code': 14001},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15001},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15002},
    {'dt_code': 'ESTOP - MCP', 'fault_code': 15003},
    {'dt_code': 'ESTOP - ZONE 1 OR ZONE 3', 'fault_code': 15004},
    {'dt_code': 'ESTOP - CONV ZONE 2', 'fault_code': 15005},
    {'dt_code': 'ESTOP - STA 11', 'fault_code': 15006},
    {'dt_code': 'ESTOP - STA 41', 'fault_code': 15007},
    {'dt_code': 'ESTOP - STA 34', 'fault_code': 15008},
    {'dt_code': 'ESTOP - STA 36', 'fault_code': 15009},
    {'dt_code': 'ESTOP - STA 47', 'fault_code': 15010},
    {'dt_code': 'ESTOP - CHARGE STA SOUTH', 'fault_code': 15011},
    {'dt_code': 'ESTOP - CHARGE STA NORTH', 'fault_code': 15012},
    {'dt_code': 'ESTOP - STA 52', 'fault_code': 15013},
    {'dt_code': 'ESTOP - STA 57', 'fault_code': 15014},
    {'dt_code': 'ESTOP - STA 24', 'fault_code': 15015},
    {'dt_code': 'ESTOP - STA 60', 'fault_code': 15016}
]


mapping_dict = {
    (item['dt_code'], item['fault_code']): item['fault_code']
    for item in New
}

def get_new_fault_code(dt_code, current_fault_code):
    return mapping_dict.get((dt_code, current_fault_code), None)

for item in Old:
    old_fault_code = item['fault_code']
    dt_code = item['dt_code']
    new_fault_code = get_new_fault_code(dt_code, old_fault_code)

    if new_fault_code is None:
        print(f"Mapping not found for DT Code: {dt_code} with Old Fault Code: {old_fault_code}")
    elif old_fault_code != new_fault_code:
        print(f"DT Code: {dt_code}, Old Fault Code: {old_fault_code}, New Fault Code: {new_fault_code}")
    else:
        print(f"No change in Fault Code for DT Code: {dt_code}, Fault Code remains: {old_fault_code}")
