import requests

webhook_url = "https://hooks.slack.com/services/XXX/XXX/XXX"

# Open the file and read its contents
with open("Slam Report\SLAM Report.xlsx", "rb") as file:
    file_content = file.read()

payload = {
    "text": "Here is the .xlsm file you requested",
    "files": [
        {
            "content": file_content,
            "filename": "Slam Report.xlsm"
        }
    ]
}

requests.post(webhook_url, json=payload)


# API token link https://api.slack.com/authentication/token-types#bot

'''The webhook URL is a unique URL that is generated by Slack when you create a webhook. You can find the webhook URL in the Slack API dashboard for your app.

To create a webhook using the Slack API, follow these steps:

Go to the https://api.slack.com/ page and log in to your Slack account.

Click on the "Your Apps" button in the top right corner.

Click on the name of your app.

Click on the "Incoming Webhooks" feature in the navigation menu on the left.

Click the "Activate Incoming Webhooks" toggle to turn it on.

Click the "Add New Webhook to Workspace" button.

Select a channel to post the webhook to and click the "Authorize" button.

Copy the webhook URL that is displayed. This is the URL that you will use to send messages to the Slack channel.

Once you have the webhook URL, you can use it in your Python code to send messages to the Slack channel using the requests library. Here is an example of how you can do this:'''